---
title: "Intro a Tidyverse"
output: html_document
date: "2024-01-23"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library('tidyverse')
```

```{r}
data(mpg)
mpg
```
```{r}
mpg %>% #pipe operator "luego"
  add_row(manufacturer="jeep",
          displ=2,
          year=2008,
          cyl=4,
          trans="manual(m6)",
          cty=15,
          hwy=24,
          fl="p",
          class="suv")
```
```{r}
mpg %>% 
  mutate(
    cty=cty*1.609/3.785,
    hwy=hwy*1.609/3.785,
    manufacturer=as_factor(manufacturer),
    model=as_factor(model),
  )
```
Mutate cambia todos los elementos de la columna. 
as_factor lo toma como categoría y no como texto

```{r}
mpg_editada <- mpg %>% 
  mutate_if(
    .predicate=is.character,
    .funs=as_factor
  )
mpg_editada
```
```{r}
mpg_editada2 <- mpg %>% 
  mutate_if(
    .predicate=is.character,
    .funs=as_factor
  ) %>% 
  mutate(trans=fct_lump_min(trans,20,other_level="Otros"))
mpg_editada2
```
fct_lump_min agrupa lo no común, lo que se repite menos de veinte veces dentro de other_levels y te da le posibilidad de cambiar de nombre, "Otros"

```{r}
plot(cars)
```
```{r}
mpg_editada2 %>% 
  ggplot(mapping=aes(x=displ,y=hwy)) +
  geom_point()
```

```{r}
mpg_editada2 %>% 
  ggplot() +
  geom_point(mapping=aes(x=displ, y=hwy,color=class))
```

```{r}
mpg_editada2 %>% 
  ggplot() +
  geom_point(mapping=aes(x=displ, y=hwy,shape=class))
```
```{r}
ggplot(data=mpg_editada2) +
  geom_point(mapping=aes(x=displ,
                         y=hwy,
                         color=class,
                         shape=drv,
                         size=cyl),
             alpha=0.7)
```
```{r}
library('patchwork')
```

```{r}
mpg_editada2 %>% 
  ggplot(aes(x=manufacturer,y=displ))+
  geom_boxplot()
```

Diagrama de caja.

```{r}
library('tibble')
library('tidyr')
library('stringr')
library('tsibble')
library('fable')
```

```{r}
data(world_bank_pop,package='tidyr')
pop<-world_bank_pop
head(pop)
```
```{r}
pop_tidy <- pop %>% 
  pivot_longer(cols=-c(country,indicator),
               names_to="year",values_to="value") %>% 
  
  pivot_wider(names_from=indicator,
              values_from=value) %>% 
  
  select(country,year,contains("TOTL")) %>% #selecciona country, year y todas las col que contienen TOTL
  
  rename(urban_pop=SP.URB.TOTL,total_pop=SP.POP.TOTL) %>% 
  
  mutate(rural_pop_pct=(1-urban_pop/total_pop)*100,
         country=as_factor(country),
         year=as.integer(year)
         ) %>%  #mutate crea una columna, country lo convierte a factor y año a entero
  filter(country %in% c("MEX","BRA","ARG")) %>%  #filtro que selecciona lo que ingreses
  
  as_tsibble(key=country,index=year) #lo convierte a tsibble

pop_tidy 
```
```{r}
pop_train <- pop_tidy %>% 
  filter(year<=2009)

pop_query <- pop_tidy %>% 
  filter(year>2009 & year<=2013)

pop_train_query <- pop_tidy %>% 
  filter(year<=2013)

pop_train %>%
  autoplot(total_pop) + ggtitle("Total population") + ylab("")
```


```{r}
pop_train %>%
  autoplot(rural_pop_pct) + ggtitle("Rural population(%)") + ylab("")
```

```{r}
pop_fit <- pop_train %>% 
  model('RW w/ drift' = RW(rural_pop_pct ~ drift ()),
        'TSLM w/ trend' = TSLM(rural_pop_pct ~ trend()),
        ETS=ETS(rural_pop_pct ~ error("A") + trend("A") + season("N")))
tidy(pop_fit)
```


```{r}
pop_fcst <- pop_fit %>% 
  forecast(h="4 years")

pop_fcst %>% 
  autoplot(pop_train_query) + facet_grid(cols=vars(.model), rows=vars(country), scales="free_y") + guides(color= FALSE) + ylab("Rural population (%)")

# 
```

```{r}
pop_fit2 <- pop_train %>% 
  model('RW w/ drift' = RW(rural_pop_pct ~ drift()),
        'TSLM w/ trend' = TSLM(rural_pop_pct ~ trend()),
        ETS= ETS(rural_pop_pct ~ error("A") + trend("A") + season("N")) )

pop_fcst2 <- pop_fit %>% 
  forecast(h="4 years")

pop_fcst2 %>% 
  autoplot(pop_train_query) + facet_grid(cols=vars(.model), rows=vars(country), scales="free_y") +
  guides(color=FALSE) + ylab("Rural population (%)")
```

```{r}
accuracy(pop_fcst2, pop_train_query) %>% 
  arrange(country, MAPE)
```
```{r}
pop_train %>% 
  model(ETS= ETS(rural_pop_pct ~ error("A") + trend("A") + season("N"))) %>% 
  forecast(h="12 years") %>% 
  autoplot(pop_tidy) + geom_vline(xintercept = 2014, linetype="dashed", color="red") + ylab("Rural population(%)")
```

