---
title: "Proy2"
output: html_document
date: "2024-04-04"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(tidyverse)
library(tsibble)
library(feasts)
library(fable)
library(tsibbledata)
library(fpp3)
library(patchwork)
```

```{r}
vic_elec
```


```{r}
p <- vic_elec %>% 
  autoplot(Demand)

plotly::ggplotly(p)
```

```{r}
s_y <- vic_elec %>% 
  gg_season(Demand, period = "year")
s_w <- vic_elec %>% 
  gg_season(Demand, period = "week")
s_d <- vic_elec %>% 
  gg_season(Demand, period = "day")

s_y / s_w / s_d
```


# S&P 500

```{r}
library(tidyquant)
library(tidyverse)
library(tsibble)
library(fable)
library(feasts)
data = tq_get("^GSPC", get="stock.prices", from = "2022-01-01", to = "2024-03-28") %>% select(date, adjusted) %>% as_tsibble(index = date)
```

```{r}
data
```

```{r}
calls <- data |>
  mutate(t = row_number()) |>
  update_tsibble(index = t, regular = TRUE) %>% select(t, adjusted)
calls |>
  model(
    STL(adjusted ~ season(period = 5) + season(period = 20) + season(period = 252),
        robust = TRUE)
  ) |>
  components() |>
  autoplot() + labs(x = "Observation")
```

```{r}
my_dcmp_spec <- decomposition_model(
  STL(adjusted ~ season(period = 5) + season(period = 20) + season(period = 252),
      robust = TRUE),
  ETS(season_adjust ~ season("N"))
)
fc <- calls |>
  model(my_dcmp_spec) |>
  forecast(h = 25)

plot = fc |>
  fill_gaps() |>
  autoplot(calls) +
  labs(y = "SP500",
       title = "SP500")

plot
```
```{r}
fit3 <- calls %>% 
  model(
    harmonic=ARIMA(adjusted ~ trend() + fourier(period=5,K=2) + fourier(period=252,K=10))
  )

fc <- fit3 |>
  forecast(h = 25)

fc |>
  fill_gaps() |>
  autoplot(calls) +
  labs(y = "SP500",
       title = "SP500")
```
Creo que lo que mas influye en este modelo es el periodo, el periodo de 252 ajusta mejor los datos, les da una tendencia mas clara pero no considero que se un buen modelo para este tipo de datos. 

```{r}
data_fill_na = fill_gaps(data) %>% fill(adjusted, .direction = "down")
data_fill_na
```
```{r}
comp_stl <- data_fill_na %>% 
  model(
    STL(adjusted, robust = TRUE)
  ) %>% 
  components() 

comp_stl %>% 
  autoplot()
```
```{r}
comp_stl %>% 
  autoplot(season_year)
comp_stl %>% 
  autoplot(season_week)
comp_stl %>% 
  ggplot(aes(x = date, y = season_adjust)) +
  geom_line()
```
```{r}
my_dcmp_spec <- decomposition_model(
  STL(adjusted ~ season(period = 5),
      robust = TRUE),
  ETS(season_adjust)
)
fc <- data_fill_na |>
  model(my_dcmp_spec) |>
  forecast(h = 20)



plot = fc |>
  fill_gaps() |>
  autoplot(data_fill_na) +
  labs(y = "SP500",
       title = "SP500")

plot
```
```{r}
fit3 <- data_fill_na %>% 
  model(
    harmonic = ARIMA(adjusted ~ trend() + fourier(period = 5, K = 2) + fourier(period = 252, K = 20))
  )
```


```{r}
fit3 <- data_fill_na %>% 
  model(
    harmonic = ARIMA(adjusted ~ fourier(period = "week", K = 2) +
          fourier(period = "year", K = 3))
  )

```



```{r}
library(fable.prophet)
library(prophet)
colnames(data) = c("ds", "y")
```

```{r}
#fit_prophet = data %>% model(prophet=prophet(y))
prophet(data)
```

```{r}
fc <- fit_prophet %>% forecast(h=25)
fc %>% autoplot(data)
```

```{r}
fit_prophet |>
  components() |>
  autoplot()
```

```{r}
components(fit_prophet)
```

```{r}
fit_prophet = data %>% model(prophet(y ~ season(type = "additive")))

fc <- fit_prophet %>% forecast(h = 25)
fc %>% autoplot(data)
```

```{r}
fit_prophet = data %>% model(prophet(y ~ season(period = "day", order = 5) +
                                        season(period = "week", order = 2) +
                                        season(period = "year", order = 2)))


{r}
fc <- fit_prophet %>% forecast(h = 25)
fc %>% autoplot(data)

```

```{r}
?prophet
```

```{r}
index= tq_index("SP500") %>% select(symbol,weight)
index=index %>% filter(symbol!="-")
index
sum(index$weight)
```

```{r}
data=tq_get(index$symbol,get="stock.prices",from="2024-01-01",to="2024-03-29") %>% select(symbol,date,adjusted)
```











